import { createClient } from '@supabase/supabase-js';
import DOMPurify from 'dompurify';

// These will be filled in by the user after they set up Supabase
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseKey) {
    console.warn('Supabase URL or Key missing. Guestbook features will not work.');
}

export const supabase = (supabaseUrl && supabaseKey) ? createClient(supabaseUrl, supabaseKey) : null;

// Security Stamp for large media files
export const MEDIA_STAMP = 'JP-OS-MEDIA-STAMP:';

export function stripStamp(content) {
    if (typeof content !== 'string') return content;
    if (content.startsWith(MEDIA_STAMP)) {
        return content.substring(MEDIA_STAMP.length);
    }
    return content;
}

export async function saveMessage(fileName, content, options = {}) {
    const { fromName } = options;

    if (!supabase) {
        throw new Error('Supabase is not initialized. Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env file and restart your dev server.');
    }

    const isImage = content.startsWith('data:image/') || content.startsWith(MEDIA_STAMP + 'data:image/');
    const isLoop = fileName.toLowerCase().endsWith('.loop');

    // Enforce character limits
    const MAX_TEXT_LENGTH = 5000;
    const MAX_IMAGE_LENGTH = 1048576; // 1MB
    const MAX_LOOP_LENGTH = 50000;

    if (isImage) {
        if (content.length > MAX_IMAGE_LENGTH + MEDIA_STAMP.length) {
            throw new Error(`Image data is too large (${Math.round(content.length / 1024)}KB). Max is 1MB.`);
        }
    } else if (isLoop) {
        if (content.length > MAX_LOOP_LENGTH + MEDIA_STAMP.length) {
            throw new Error(`Loop data is too large. Max is ${MAX_LOOP_LENGTH} characters.`);
        }
    } else {
        if (content.length > MAX_TEXT_LENGTH) {
            throw new Error(`Note is too long. Max is ${MAX_TEXT_LENGTH} characters.`);
        }
    }

    // Security Reality Check: Anything over 5000 chars MUST have the media stamp
    if (content.length > MAX_TEXT_LENGTH && !content.startsWith(MEDIA_STAMP)) {
        throw new Error('Security Error: Large files must be generated by a JP-OS app.');
    }

    // We only sanitize if it's NOT an image. 
    // DOMPurify on a 1MB base64 string is extremely slow and can corrupt the image data.
    const sanitizedContent = isImage ? content : DOMPurify.sanitize(content);
    const sanitizedFileName = DOMPurify.sanitize(fileName);

    // Sanitize and cap the from_name (max 100 chars)
    const sanitizedFromName = fromName
        ? DOMPurify.sanitize(String(fromName)).trim().substring(0, 100) || null
        : null;

    // Basic Validation: If it's a .draw file, it MUST be an image
    if (sanitizedFileName.toLowerCase().endsWith('.draw') && !isImage) {
        throw new Error('Security: .draw files must be valid image data.');
    }

    const { data, error } = await supabase
        .from('messages')
        .insert([
            {
                filename: sanitizedFileName,
                content: sanitizedContent,
                ...(sanitizedFromName ? { from_name: sanitizedFromName } : {})
            }
        ])
        .select(); // Return the inserted row so callers can get the ID

    if (error) throw error;
    return data;
}

export async function binMessage(messageId) {
    if (!supabase) return;
    console.log(`Binning message: ${messageId}`);

    const { data: updated, error } = await supabase.rpc('bin_message', { message_id: messageId });

    if (error) {
        console.warn('RPC failed:', error);
        const { data: updateData, error: updateError } = await supabase
            .from('messages')
            .update({ is_binned: true, bin_count: 1 })
            .eq('id', messageId)
            .select();

        if (updateError) {
            console.error('Direct binning failed:', updateError);
            throw updateError;
        }
        return updateData;
    }

    if (updated === false) {
        console.error(`Database found NO record for ID ${messageId}! Binning failed.`);
    } else {
        console.log('Successfully binned in DB');
    }
    return updated;
}

export async function restoreMessage(messageId) {
    if (!supabase) return;
    console.log(`Restoring message: ${messageId}`);

    const { data: restored, error } = await supabase.rpc('restore_message', { message_id: messageId });

    if (error) {
        console.warn('RPC restoration failed:', error);
        // Fallback to direct update if RPC fails
        const { data: updateData, error: updateError } = await supabase
            .from('messages')
            .update({ is_binned: false })
            .eq('id', messageId)
            .select();

        if (updateError) {
            console.error('Direct restoration failed:', updateError);
            throw updateError;
        }
        return updateData;
    }

    return restored;
}

export async function deleteMessagePermanently(messageId) {
    if (!supabase) return;

    const { data, error } = await supabase
        .from('messages')
        .delete()
        .eq('id', messageId);

    if (error) throw error;
    return data;
}

export async function getMessages() {
    if (!supabase) {
        // Return empty array if not configured, rather than crashing
        console.warn('Attempted to fetch messages but Supabase is not configured.');
        return [];
    }

    const { data, error } = await supabase
        .from('messages')
        .select('*')
        .or('is_binned.eq.false,is_binned.is.null')
        .order('created_at', { ascending: false })
        .limit(50); // Prevent loading hundreds of MBs if spammed

    if (error) {
        console.error('Error fetching guestbook messages:', error);
        return [];
    }
    return data;
}

// ============================================================
// SITE SETTINGS (wallpaper, future global state)
// ============================================================

export async function getSetting(key) {
    if (!supabase) return null;
    const { data, error } = await supabase
        .from('site_settings')
        .select('value, metadata')
        .eq('key', key)
        .maybeSingle();
    if (error) { console.error('getSetting error:', error); return null; }
    return data;
}

export async function setSetting(key, value, metadata = {}) {
    if (!supabase) return;
    const { error } = await supabase.rpc('set_site_setting', {
        p_key: key,
        p_value: value,
        p_metadata: metadata
    });
    if (error) throw error;
}

export async function clearSetting(key) {
    if (!supabase) return;
    const { error } = await supabase.rpc('clear_site_setting', { p_key: key });
    if (error) throw error;
}

/**
 * Subscribe to realtime changes for a specific setting key.
 * @param {string} key - The setting key to watch (e.g. 'wallpaper')
 * @param {function} callback - Called with { value, metadata } whenever the row changes
 * @returns {object} Supabase channel - call .unsubscribe() to clean up
 */
export function subscribeToSetting(key, callback) {
    if (!supabase) return null;
    const channel = supabase
        .channel(`site_settings:${key}`)
        .on(
            'postgres_changes',
            {
                event: '*',
                schema: 'public',
                table: 'site_settings',
                filter: `key=eq.${key}`
            },
            (payload) => {
                const row = payload.new || {};
                callback({ value: row.value ?? null, metadata: row.metadata ?? {} });
            }
        )
        .subscribe();
    return channel;
}

// Wallpaper convenience wrappers
export const getWallpaper = () => getSetting('wallpaper');
export const setWallpaper = (dataUrl, sourceMessageId = null) =>
    setSetting('wallpaper', dataUrl, sourceMessageId ? { source_message_id: sourceMessageId } : {});
export const clearWallpaper = () => clearSetting('wallpaper');
export const subscribeToWallpaper = (callback) => subscribeToSetting('wallpaper', callback);

export async function getBinnedMessages() {
    if (!supabase) return [];

    const { data, error } = await supabase
        .from('messages')
        .select('*')
        .eq('is_binned', true)
        .order('created_at', { ascending: false })
        .limit(50);

    if (error) {
        console.error('Error fetching binned messages:', error);
        return [];
    }
    return data;
}

export function formatDate(dateStr) {
    if (!dateStr) return '';
    try {
        const date = new Date(dateStr);
        return new Intl.DateTimeFormat('en-US', {
            month: 'long',
            day: 'numeric',
            year: 'numeric'
        }).format(date);
    } catch (e) {
        return '';
    }
}

